---
title: "Final Project"
execute: 
  echoe: false
  message: false
---

This is a Quarto website.

To learn more about Quarto websites visit <https://quarto.org/docs/websites>.

```{r}
library(readxl)
library(tidyverse)
library(writexl)
library(stringr)
library(rstanarm)
```

```{r}
prem <- read_excel("EPL_Payroll.xlsx")
```

```{r}
x <- prem |>
  select("Season", "Rk", "Squad", "Annual Wages", "Standing") |>
  mutate(annual = str_extract(`Annual Wages`, "\\$[0-9,]+")) |>
  mutate(annual = as.numeric(gsub("[$,]", "", annual))) |>
  select(-`Annual Wages`)

```

```{r}
x
```


```{r}
fit_1 <- stan_glm(Standing ~ Rk,
                  data = x,
                  family = gaussian,
                  refresh = 0)

```

```{r}
fit_1
```
```{r}
loo(fit_1)
loo(fit_2)
```


```{r}
newobs <- tibble(Rk = 1:20)

pe <- posterior_epred(fit_1, newdata = newobs) |> 
  as_tibble() |>
  pivot_longer(cols = `1`:`20`,
               names_to = "rank",
               values_to = "standing") 
pe |>
  ggplot(aes(x = rank, y = standing)) +
  geom_point(alpha = 0.5) 
  

pe

```


```{r}
x |>
  ggplot(aes(x = Rk, y = Standing)) +
  geom_jitter(alpha = 0.5) +
  scale_x_reverse() +
  scale_y_reverse() +
  geom_smooth(method = "lm", se = FALSE) +
  labs(title = "Payroll Rank vs. Season Standing in the EPL",
       subtitle = "There is a positive correlation between the two",
       x = "Payroll Rank",
       y = "Season Standing")
```

```{r}
x |>
  summarise(.by = Season, total = sum(annual)) |>
  ggplot(aes(x = Season, y = total)) +
  geom_point() +
  geom_smooth(se = FALSE, method = "lm") +
  labs(title = "Total Amount of Money Spent Across Seasons in EPL",
       subtitle = "The league has steadily spent more money on players",
       y= "Total Paid") +
  scale_y_continuous(labels = scales::dollar_format())
  scale_x_continuous(breaks = seq(2013, 2022, by = 1), limits = c(2013, 2022))
```

```{r}
summary(fit_1)
```

```{r}
prem |>
  filter(Rk == 1) |>
  select(Squad, Season, Standing)
```

