---
title: "bundesliga"
editor: visual
---
```{r}
library(readxl)
library(tidyverse)
library(writexl)
library(stringr)
library(rstanarm)
library(ggthemes)
library(plotly)
library(formattable)
```

```{r}
bundesliga <- read_excel("Bundesliga_Payroll.xlsx")
```

```{r}
y <- bundesliga |>
  select("Season", "Rk", "Squad", "Annual Wages", "Standing") |>
  mutate(annual = str_extract(`Annual Wages`, "\\$[0-9,]+")) |>
  mutate(annual = as.numeric(gsub("[$,]", "", annual))) |>
  select(-`Annual Wages`)
```

```{r}
y
```
```{r}
y_1 <- y |>
  summarise(.by = Season, Rk = Rk, Squad = Squad, Standing = Standing, annual = annual, percent = annual/sum(annual))
```



```{r}
fit_2 <- stan_glm(Standing ~ Rk,
                  data = y,
                  family = gaussian,
                  refresh = 0)

fit_3 <- stan_glm(Standing ~ Rk + percent,
                  data = y_1,
                  family = gaussian,
                  refresh = 0)

```

```{r}
fit_2
fit_3
```

```{r}
loo_compare(loo(fit_2), loo(fit_3))
```


```{r}
newobs <- tibble(Rk = 1:20)

pe_2 <- posterior_epred(fit_2, newdata = newobs) |> 
  as_tibble() |>
  pivot_longer(cols = `1`:`20`,
               names_to = "rank",
               values_to = "standing") |>
  mutate_all(as.numeric)

pe_2 |>
  ggplot(aes(x = rank, y = standing)) +
  geom_point(alpha = 0.5) 
  

pe_2
```

```{r}
y_1 <- y |>
  ggplot(aes(x = Rk, y = Standing)) +
  geom_jitter(alpha = 0.5) +
  scale_x_reverse(breaks = seq(20, 1, by = -1)) +
  scale_y_reverse(breaks = seq(20, 1, by = -1)) +
  geom_smooth(method = "lm", se = FALSE) +
  labs(title = "Payroll Rank vs. Season Standing in the Bundesliga",
       subtitle = "There is a positive correlation between the two",
       x = "Payroll Rank",
       y = "Season Standing") 
```

```{r}
y_1 |>
  ggplotly()
```


```{r}
top5 <- read_excel("Top5Leagues_Payroll.xlsx")
top5
```

```{r}
a <- top5 |>
  select(-c("# Pl", "Weekly Wages", "% Estimated", "Squad (again)")) |>
  mutate(annual = str_extract(`Annual Wages`, "\\$[0-9,]+")) |>
  mutate(annual = as.numeric(gsub("[$,]", "", annual))) |>
  select(-`Annual Wages`) |>
  filter(Season >= 2013) |>
  summarise(.by = c(League, Season), total = sum(annual))
  
```

```{r}
a |>
  ggplot(aes(x = Season, y = total, color = League)) +
  geom_point() +
  geom_line() +
  theme_classic()
```
```{r}
b <- top5 |>
  select(-c("# Pl", "Weekly Wages", "% Estimated", "Squad (again)")) |>
  mutate(annual = str_extract(`Annual Wages`, "\\$[0-9,]+")) |>
  mutate(annual = as.numeric(gsub("[$,]", "", annual))) |>
  select(-`Annual Wages`) |>
  filter(Season >= 2013, Standing <= 4 | Standing >= 18) |>
  mutate(top = Standing <= 4)
```

```{r}
c <- b |>
  ggplot(aes(x = Season, y = annual, color = top, text = paste("Season:", Season, "\n", 
                                                               "Payroll:", currency(annual), "\n",
                                                               "Standing:", Standing, "\n",
                                                               "Team:", Squad))) +
  geom_point(alpha = 0.5) +
  scale_y_continuous(labels = scales::dollar_format()) +
  labs(title = "Payroll of Top Four vs Bottom Three Teams in Each Season",
       subtitle = "The payroll gap of top from bottom has steadily increased",
       y = "Payroll",
       color = "Top Four")
```

```{r}
c |>
  ggplotly(tooltip = "text")
```

```{r}
differential <- top5 |>
  select(-c("# Pl", "Weekly Wages", "% Estimated", "Squad (again)")) |>
  mutate(annual = str_extract(`Annual Wages`, "\\$[0-9,]+")) |>
  mutate(annual = as.numeric(gsub("[$,]", "", annual))) |>
  select(-`Annual Wages`) |>
  mutate(diff = Rk - Standing) |>
  summarise(.by = Squad, total = sum(diff), years = n()) 
```

```{r}
differential |>
  arrange(desc(total))
```

